
[target.i686-pc-windows-msvc.freetype]
rustc-link-search = ["./crystal-sphinx/temportal-engine/editor/bin/freetype/i686"]
rustc-link-lib = ["freetype"]

[target.x86_64-pc-windows-msvc.freetype]
rustc-link-search = ["./crystal-sphinx/temportal-engine/editor/bin/freetype/x86_64"]
rustc-link-lib = ["freetype"]
